general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 14.0
  [font.normal]
  family = "GoogleSansCode Nerd Font Mono"
  style = "Medium"
  [font.italic]
  family = "GoogleSansCode Nerd Font Mono"
  style = "Medium Italic"
  [font.bold]
  family = "GoogleSansCode Nerd Font Mono"
  style = "Bold"
  [font.bold_italic]
  family = "GoogleSansCode Nerd Font Mono"
  style = "Bold Italic"

[env]
TERM = "xterm-256color"
