general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 14.0
[font.normal]
family = "Google Sans Code"
style = "Medium"
[font.italic]
family = "Google Sans Code"
style = "Medium Italic"
[font.bold]
family = "Google Sans Code"
style = "Bold"
[font.bold_italic]
family = "Google Sans Code"
style = "Bold Italic"

[env]
TERM = "xterm-256color"
